#!/bin/sh
# Regenerate conformance_cases.inc from cases.txt by asking jq what each
# program actually produces. Run this; never edit the .inc by hand - the whole
# point is that the expectations come from the reference implementation.
#
#   sh tests/gen-cases.sh > tests/conformance_cases.inc
#
# jq -S sorts object keys, because jk holds objects in an ordered map while jq
# preserves insertion order. Nothing else about the comparison is relaxed.
set -e
DIR=$(dirname "$0")

command -v jq >/dev/null 2>&1 || { echo "jq is required" >&2; exit 1; }

# Escape for a C string literal: backslashes and quotes first, then join the
# lines of a multi-value result with a two-character \n. Doing it in the other
# order would escape the joiner itself.
esc() {
  printf '%s' "$1" \
    | sed 's/\\/\\\\/g; s/"/\\"/g' \
    | awk 'NR>1 { printf "\\n" } { printf "%s", $0 }'
}

printf '// Generated by gen-cases.sh from cases.txt against jq %s. Do not edit.\n' \
  "$(jq --version)"

while IFS='	' read -r prog input; do
  case "$prog" in
    ''|'#'*) continue ;;
  esac
  [ -n "$input" ] || continue

  if out=$(printf '%s' "$input" | jq -cS "$prog" 2>/dev/null); then
    expected="$out"
  else
    expected='<error>'
  fi

  printf '{"%s", "%s", "%s"},\n' \
    "$(esc "$prog")" "$(esc "$input")" "$(esc "$expected")"
done < "$DIR/cases.txt"
