#!/bin/sh
# Regenerate conformance_cases.inc from cases.txt by asking jq what each
# program actually produces. Run this; never edit the .inc by hand - the whole
# point is that the expectations come from the reference implementation.
#
#   sh tests/gen-cases.sh > tests/conformance_cases.inc
#
# jq -S sorts object keys, because jk holds objects in an ordered map while jq
# preserves insertion order. Result order and terminal status remain significant.
set -e
DIR=$(dirname "$0")

JQ=${JQ:-jq}
command -v "$JQ" >/dev/null 2>&1 || { echo "jq 1.8.2 is required" >&2; exit 1; }
[ "$("$JQ" --version)" = "jq-1.8.2" ] || {
  echo "Expected official jq-1.8.2; set JQ to its executable" >&2
  exit 1
}

# Escape for a C string literal: backslashes and quotes first, then join the
# lines of a multi-value result with a two-character \n. Doing it in the other
# order would escape the joiner itself.
esc() {
  printf '%s' "$1" \
    | sed 's/\\/\\\\/g; s/"/\\"/g' \
    | awk 'NR>1 { printf "\\n" } { printf "%s", $0 }'
}

printf '// Generated by gen-cases.sh from cases.txt against jq %s. Do not edit.\n' \
  "$("$JQ" --version)"

while IFS='	' read -r prog input; do
  case "$prog" in
    ''|'#'*) continue ;;
  esac
  [ -n "$input" ] || continue

  status=0
  out=$(printf '%s' "$input" | "$JQ" -cS "$prog" 2>/dev/null) || status=$?
  case "$status" in
    0|3|5) ;;
    *) echo "Unexpected jq exit status $status for $prog" >&2; exit 1 ;;
  esac

  printf '{"%s", "%s", "%s", %s},\n' \
    "$(esc "$prog")" "$(esc "$input")" "$(esc "$out")" "$status"
done < "$DIR/cases.txt"
